<<<<<<< HEAD
# Generated by Django 3.2 on 2021-04-09 01:10
=======
# Generated by Django 2.2 on 2021-03-23 19:13
>>>>>>> b9f4a318b4f2c08c5d659803cc2198ce28f12e08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(verbose_name='Fecha de creacion')),
                ('admin_creador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Catalogos',
            },
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='Consummer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('middleName', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
=======
>>>>>>> b9f4a318b4f2c08c5d659803cc2198ce28f12e08
            name='ItemCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('visibilidad', models.BooleanField()),
<<<<<<< HEAD
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mercadoOrganicosApp.catalogo')),
=======
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mercadoOrganicosApp.Catalogo')),
>>>>>>> b9f4a318b4f2c08c5d659803cc2198ce28f12e08
            ],
            options={
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
<<<<<<< HEAD
                ('fecha_creacion', models.DateTimeField()),
                ('precio', models.FloatField()),
                ('itemCompra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mercadoOrganicosApp.itemcompra')),
=======
                ('precio', models.FloatField()),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mercadoOrganicosApp.ItemCompra')),
>>>>>>> b9f4a318b4f2c08c5d659803cc2198ce28f12e08
            ],
            options={
                'verbose_name_plural': 'Productos',
            },
        ),
<<<<<<< HEAD
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consummer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mercadoOrganicosApp.consummer')),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mercadoOrganicosApp.producto')),
            ],
        ),
=======
>>>>>>> b9f4a318b4f2c08c5d659803cc2198ce28f12e08
    ]
