# Generated by Django 3.1.6 on 2021-05-05 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercadoOrganicosApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='item_compras',
        ),
        migrations.CreateModel(
            name='Carrito_ItemCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mercadoOrganicosApp.carrito')),
                ('item_compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mercadoOrganicosApp.itemcompra')),
            ],
            options={
                'verbose_name_plural': 'CarritoItemCompra',
            },
        ),
        migrations.AddField(
            model_name='carrito',
            name='item_compra',
            field=models.ManyToManyField(through='mercadoOrganicosApp.Carrito_ItemCompra', to='mercadoOrganicosApp.ItemCompra'),
        ),
    ]
